flowchart LR
    classDef in fill:#E3F2FD,stroke:#2196F3,stroke-width:2px;
    classDef para fill:#FFF9C4,stroke:#FBC02D,stroke-width:2px;
    classDef act fill:#E1BEE7,stroke:#9C27B0,stroke-width:2px;
    classDef func fill:#F8BBD0,stroke:#E91E63,stroke-width:2px;
    classDef out fill:#DCEDC8,stroke:#8BC34A,stroke-width:2px;
    classDef skip stroke:#B0BEC5,stroke-width:2px,stroke-dasharray: 5 5;

    X1((x<sub>1</sub>)):::in
    X2((x<sub>2</sub>)):::in
    M1("H<sub>1</sub>"):::para
    M2("H<sub>2</sub>"):::para
    M3("H<sub>3</sub>"):::para
    M4("H<sub>4</sub>"):::para
    W1((m<sub>1</sub>)):::act
    W2((m<sub>2</sub>)):::act
    W3((m<sub>3</sub>)):::act
    W4((m<sub>4</sub>)):::act
    M5("O"):::para
    Y((y)):::out

    X1 --> M1
    X1 --> M2
    X1 --> M3
    X1 --> M4
    X2 --> M1
    X2 --> M2
    X2 --> M3
    X2 --> M4
    M1 --> W1
    M2 --> W2
    M3 --> W3
    M4 --> W4
    W1 --> M5
    W2 --> M5
    W3 --> M5
    W4 --> M5
    M5 --> Y
