block-beta
classDef transparent fill:white,stroke:white
classDef in fill:#E3F2FD,stroke:#2196F3,stroke-width:2px;
classDef model fill:#FFF9C4,stroke:#FBC02D,stroke-width:2px;
classDef data fill:#E1BEE7,stroke:#9C27B0,stroke-width:2px;
classDef test fill:#F8BBD0,stroke:#E91E63,stroke-width:2px;
classDef out fill:#DCEDC8,stroke:#8BC34A,stroke-width:2px;
classDef skip stroke:#B0BEC5,stroke-width:2px,stroke-dasharray: 5 5;
columns 3
block:x_3:3
    columns 4
    x3_1["x"]
    x3_2["x"]
    x3_3["x"]
    x3_4["x"]
    x3_5["x"]
    x3_6["x"]
    x3_7["x"]
    x3_8["x"]
    x3_9["x"]
    x3_10["x"]
    x3_11["x"]
    x3_12["x"]
    x3_13["x"]
    x3_14["x"]
    x3_15["x"]
    x3_16["x"]
    space
    space
    arrow3<["&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"]>(down)
end

class x3_1,x3_2,x3_5,x3_6,x3_9,x3_10,x3_11,x3_12,x3_13,x3_14,x3_15,x3_16 in
class x3_3,x3_4,x3_7,x3_8 in
class x_3,arrow3 transparent
